

project_id = "qszqzdnlhxpglllyqtht"

[api]
port = 54321
schemas = ["public", "auth", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
# Global settings for all edge functions
[functions.global]
verify_jwt = true
